"$schema" = 'https://starship.rs/config-schema.json'

command_timeout=1000
format = """
$os\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:red)\
$c\
$elixir\
$lua\
$nodejs\
$python\
$ruby\
$rust\
[](fg:red bg:overlay2)\
$time\
[ ](fg:overlay2)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[os]
disabled = false
style = "fg:crust bg:yellow"

[os.symbols]
Arch = " "
Macos = " "
Windows = " 󰍲"

[directory]
truncate_to_repo = false
style = "fg:crust bg:yellow"
format = "[  $path]($style)"

[git_branch]
symbol = "   "
style = "fg:crust bg:green"
format = '[$symbol$branch]($style)'

[git_status]
style = "fg:crust bg:green"
ahead = '⇡${count}'
behind = '⇣${count}'
conflicted = '=${count}'
deleted = '✘${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
modified = '!${count}'
renamed = '»${count}'
staged = '+${count}'
stashed = '\$${count}'
untracked = '?${count}'
format = '[[( $all_status $ahead_behind )](fg:crust bg:green)]($style)'

[time]
disabled = false
time_format = "%r %a %b %d %Y"
style = "fg:crust bg:overlay2"
format = '[[  $time]($style)]($style)'

[line_break]
disabled = false

[character]
disabled = false
# Note the use of Catppuccin color 'peach'
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode
vimcmd_replace_one_symbol = '[󰄛 ❮](bold fg:mauve)'
vimcmd_replace_symbol = '[󰄛 ❮](bold fg:mauve)'
vimcmd_visual_symbol = '[󰄛 ❮](bold fg:yellow)'

############## NERD FONT SYMBOLS ###############
[c]
symbol = " "
style = "fg:crust bg:red"
format = '[[ $symbol($version) ]($style)]($style)'

[elixir]
symbol = " "
style = "fg:crust bg:red"
format = '[[ $symbol($version) ]($style)]($style)'

[lua]
symbol = " "
style = "fg:crust bg:red"
format = '[[ $symbol($version) ]($style)]($style)'

[nodejs]
symbol = " "
style = "fg:crust bg:red"
format = '[[ $symbol($version) ]($style)]($style)'

[python]
symbol = " "
style = "fg:crust bg:red"
format = '[[ $symbol($version) ]($style)]($style)'

[ruby]
symbol = " "
style = "fg:crust bg:red"
format = '[[ $symbol($version) ]($style)]($style)'

[rust]
symbol = "󱘗 "
style = "fg:crust bg:red"
format = '[[ $symbol($version) ]($style)]($style)'
