"$schema" = 'https://starship.rs/config-schema.json'

command_timeout=1000
format = """\
$os\
$directory\
$fill\
$git_branch\
$git_status\
$line_break\
$character\
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[os]
disabled = false
style = "fg:crust bg:rosewater bold"

[os.symbols]
Fedora = " "
Arch = " "
EndeavourOS = " "
Kali = " "
Macos = " "
Windows = " "

[directory]
truncate_to_repo = false
style = "fg:crust bg:rosewater bold"
format = "[  $path]($style)[](fg:rosewater bg:none)"

[fill]
symbol = " "

[git_branch]
symbol = " "
style = "fg:crust bg:green bold"
format = '[](bg:none fg:green)[$symbol$branch]($style)'

[git_status]
style = "fg:crust bg:green bold"
ahead = '⇡${count}'
behind = '⇣${count}'
conflicted = '=${count}'
deleted = '✘${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
modified = '!${count}'
renamed = '»${count}'
staged = '+${count}'
stashed = '\$${count}'
untracked = '?${count}'
format = '[[(( $all_status)( $ahead_behind)) ]($style)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[[󰄛](green bold) ❯](sapphire)"
error_symbol = "[[󰄛](red bold) ❯](sapphire)"
