#!/usr/bin/env bash

script_path=$(realpath "$0")
script_dir=$(dirname "$script_path")
project_root=$(dirname "$script_dir")

config_path="$project_root/config.psv"

link_from_path () {
  echo "$HOME/$1"
}

link_to_path () {
  echo "$project_root/files/$1"
}

tail -n +2 "$config_path" | while IFS='|' read -r description to from post_run; do
  link_from=$(link_from_path "$from")
  link_to=$(link_to_path "$to")

  echo "Installing $description"

  if ! [[ -d $(dirname "$link_from") ]]; then
    echo "Creating directory $(dirname "$link_from") for $from"
    mkdir -p "$(dirname "$link_from")"
  fi

  if [[ -L $link_from ]]; then
    echo "Unlinking existing $from"
    unlink "$link_from"
  fi

  if [[ -e $link_from ]]; then
    echo "Backing up existing $from to $from.old"
    mv "$link_from" "$link_from.old"
  fi

  echo "Linking $link_from to $link_to"
  ln -sf "$link_to" "$link_from"

  if [[ -n $post_run ]]; then
    string="stirng" ; echo "${string//ir/ri}"

    post_run_cmd=$("${post_run//LINK_PATH/$link_from}")
    echo "Running post-link command: $post_run_cmd"
    eval "$post_run_cmd"
  fi

  echo "----------"
done
