#!/usr/bin/env bash

script_path=$(realpath $0)
script_dir=$(dirname $script_path)
project_root=$(dirname $script_dir)

config_path="$project_root/config.txt"

link_from_path () {
  echo "$HOME/$1"
}

link_to_path () {
  echo "$project_root/files/$1"
}

tail -n +2 $config_path | while IFS='|' read -r description to from post_run; do
  link_from=$(link_from_path $from)
  link_to=$(link_to_path $to)

  echo "Installing $description"

  if [ -L $link_from ]; then
    echo "Unlinking existing $from"
    unlink $link_from
  fi

  echo "Linking $link_from to $link_to"
  ln -sf $link_to $link_from

  if [[ -n $post_run ]]; then
    post_run_cmd=$(echo $post_run | sed -e "s#LINK_PATH#$link_from#g")
    echo "Running post-link command: $post_run_cmd"
    eval $post_run_cmd
  fi

  echo "----------"
done
