[mgr]
ratio = [1, 2, 2]
show_hidden = true
show_symlink = true
sort_by = "alphabetical"
sort_sensitive = false
sort_dir_first = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
