[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 4
y = 4

[env]
TERM = "xterm-256color"

[font]
size = 18.0
