[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.90
blur = false
option_as_alt = "Both"

[window.padding]
x = 8
y = 8

[env]
TERM = "xterm-256color"

[font]
size = 18.0
normal.family = "JetBrainsMonoNL Nerd Font Mono"
# normal.family = "MesloLGS Nerd Font Mono"
